### ISSUE TITLE
Spammy pyepics warning and errors when there is a problem

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/Bug-Reports-and-Requests#30]
**Bug Report**

Super spam
```
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py:1524: UserWarning: ca.get('XPP:SB3:JAWS:DMOV') timed out after 10.00 seconds.
  warnings.warn(msg % (name(chid), timeout))
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py:1524: UserWarning: ca.get('XPP:SB3:JAWS:ACTUAL_XWIDTH') timed out after 10.00 seconds.
  warnings.warn(msg % (name(chid), timeout))
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py:1524: UserWarning: ca.get('XPP:SB3:JAWS:XCEN_REQ') timed out after 5.00 seconds.
  warnings.warn(msg % (name(chid), timeout))
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py:1524: UserWarning: ca.get('XPP:SB3:JAWS:XCEN_REQ') timed out after 1.00 seconds.
  warnings.warn(msg % (name(chid), timeout))
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py:1524: UserWarning: ca.get('XPP:SB3:JAWS:YCEN_REQ') timed out after 5.00 seconds.
  warnings.warn(msg % (name(chid), timeout))
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py:1524: UserWarning: ca.get('XPP:SB3:JAWS:YCEN_REQ') timed out after 1.00 seconds.
  warnings.warn(msg % (name(chid), timeout))
In [1]: CA.Client.Exception...............................................
    Warning: "Virtual circuit unresponsive"
    Context: "ioc-xpp-mot01.pcdsn:58719"
    Source File: ../tcpiiu.cpp line 925
    Current Time: Wed Aug 19 2020 09:46:17.612059049
..................................................................
ERROR    Exception occurred during callback <function PyepicsShimPV.get_all_metadata_callback.<locals>.get_metadata_thread at 0x7f8bd86a2bf8> (pvname='XPP:SB3:JAWS:XWID_REQ')
Traceback (most recent call last):
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/ophyd/_dispatch.py", line 45, in run
    callback(*args, **kwargs)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/ophyd/_pyepics_shim.py", line 105, in get_metadata_thread
    md = self.get_all_metadata_blocking(timeout=timeout)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/ophyd/_pyepics_shim.py", line 97, in get_all_metadata_blocking
    self.get_timevars(timeout=timeout)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/pv.py", line 48, in wrapped
    return func(self, *args, **kwargs)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/pv.py", line 746, in get_timevars
    kwds = ca.get_timevars(self.chid, timeout=timeout, warn=warn)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 579, in wrapper
    return fcn(*args, **kwds)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 1787, in get_timevars
    wait=True)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 637, in wrapper
    return fcn(*args, **kwds)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 1392, in get_with_metadata
    as_numpy=as_numpy)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 637, in wrapper
    return fcn(*args, **kwds)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 1533, in get_complete_with_metadata
    raise get_failure_reason
epics.ca.ChannelAccessGetFailure: Get failed; status code: 192
ERROR    Exception occurred during callback <function PyepicsShimPV.get_all_metadata_callback.<locals>.get_metadata_thread at 0x7f8bf6c160d0> (pvname='XPP:SB3:JAWS:DMOV')
Traceback (most recent call last):
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/ophyd/_dispatch.py", line 45, in run
    callback(*args, **kwargs)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/ophyd/_pyepics_shim.py", line 105, in get_metadata_thread
    md = self.get_all_metadata_blocking(timeout=timeout)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/ophyd/_pyepics_shim.py", line 97, in get_all_metadata_blocking
    self.get_timevars(timeout=timeout)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/pv.py", line 48, in wrapped
    return func(self, *args, **kwargs)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/pv.py", line 746, in get_timevars
    kwds = ca.get_timevars(self.chid, timeout=timeout, warn=warn)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 579, in wrapper
    return fcn(*args, **kwds)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 1787, in get_timevars
    wait=True)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 637, in wrapper
    return fcn(*args, **kwds)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 1392, in get_with_metadata
    as_numpy=as_numpy)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 637, in wrapper
    return fcn(*args, **kwds)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 1533, in get_complete_with_metadata
    raise get_failure_reason
epics.ca.ChannelAccessGetFailure: Get failed; status code: 192
ERROR    Exception occurred during callback <function PyepicsShimPV.get_all_metadata_callback.<locals>.get_metadata_thread at 0x7f8b05d42ea0> (pvname='XPP:SB3:JAWS:ACTUAL_YWIDTH')
Traceback (most recent call last):
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/ophyd/_dispatch.py", line 45, in run
    callback(*args, **kwargs)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/ophyd/_pyepics_shim.py", line 105, in get_metadata_thread
    md = self.get_all_metadata_blocking(timeout=timeout)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/ophyd/_pyepics_shim.py", line 97, in get_all_metadata_blocking
    self.get_timevars(timeout=timeout)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/pv.py", line 48, in wrapped
    return func(self, *args, **kwargs)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/pv.py", line 746, in get_timevars
    kwds = ca.get_timevars(self.chid, timeout=timeout, warn=warn)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 579, in wrapper
    return fcn(*args, **kwds)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 1787, in get_timevars
    wait=True)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 637, in wrapper
    return fcn(*args, **kwds)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 1392, in get_with_metadata
    as_numpy=as_numpy)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 637, in wrapper
    return fcn(*args, **kwds)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 1533, in get_complete_with_metadata
    raise get_failure_reason
epics.ca.ChannelAccessGetFailure: Get failed; status code: 192
ERROR    Exception occurred during callback <function PyepicsShimPV.get_all_metadata_callback.<locals>.get_metadata_thread at 0x7f8bf6890840> (pvname='XPP:SB3:JAWS:YWID_REQ')
Traceback (most recent call last):
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/ophyd/_dispatch.py", line 45, in run
    callback(*args, **kwargs)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/ophyd/_pyepics_shim.py", line 105, in get_metadata_thread
    md = self.get_all_metadata_blocking(timeout=timeout)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/ophyd/_pyepics_shim.py", line 97, in get_all_metadata_blocking
    self.get_timevars(timeout=timeout)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/pv.py", line 48, in wrapped
    return func(self, *args, **kwargs)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/pv.py", line 746, in get_timevars
    kwds = ca.get_timevars(self.chid, timeout=timeout, warn=warn)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 579, in wrapper
    return fcn(*args, **kwds)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 1787, in get_timevars
    wait=True)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 637, in wrapper
    return fcn(*args, **kwds)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 1392, in get_with_metadata
    as_numpy=as_numpy)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 637, in wrapper
    return fcn(*args, **kwds)
  File "/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.2/lib/python3.6/site-packages/epics/ca.py", line 1533, in get_complete_with_metadata
    raise get_failure_reason
epics.ca.ChannelAccessGetFailure: Get failed; status code: 192
```
**Expected Behavior**

Only warn once? Don't explode?

**Context**

Annoying

**Steps To Reproduce**

1. xpppython/xpp3
2.
3.
4.

**Your Environment**

**Comment by klauer** [comment]
I don't think I've ever even seen a `caget` failure through pyepics, so it's interesting this exercised that code path.

Tracing back the error code, it looks like the virtual circuit disconnected (`ECA_DISCONN = 192`).

It seems like after restarting the IOC, that specific message was resolved, right?

**Comment by ZLLentz** [comment]
Yes, this is OK now. The IOC was "running" but clearly having a bad time.

**Comment by klauer** [comment]
To be honest, I'm kinda happy that the rare error is so noisy here, but not so happy it wasn't reported to us directly.

Perhaps we should catch `ChannelAccessGetFailure` and make a more friendly log entry saying: *"you probably should restart your IOC before calling us!"*
